Outstanding changes from my fork
MicrosoftLearning/MB-320-Microsoft-Dynamics-365-Supply-Chain-Management-Manufacturing pull request #67
Opened 2023-03-30 09:43 UTC by ephiax20

# Module: 2
## Lab/Demo: All

Changes proposed in this pull request:

- Mainly click/select and type/enter changes.
- Other minor text formatting or layout changes.

2023-04-20 23:32 UTC, mstall1ngs requested changes
Thanks for the testing, Simon! Please review the changes and make updates prior to merging.

2023-04-20 23:32 UTC, mstall1ngs commented on Instructions/Labs/M2 Manage manufacturing processes.md
> -13. Select **Journals**.
Update Step 13 to: Expand the Line details FastTab.
![image](https://user-images.githubusercontent.com/104943975/233506623-4951818b-baa9-402a-b029-dd6d2d528299.png)
14. Select the **Dimension** tab
15. Select **Edit**.
16. Select to follow the link in the **Batch number** field
17. Select **New**
18. In the **Batch number** field, enter or select a value.
19. Select **Save**.
20. In the **Expiration date** field, enter a date.
Continue with renumbering. This exercise should have 32 steps after you've updated this.

2023-04-21 07:51 UTC, ephiax20 commented on Instructions/Labs/M2 Manage manufacturing processes.md
> +9.  In the **Next** field, enter **20**.
Hi,

The additional space is meant to align the Content for Tasks with more than 9 steps, to make it easier to read in the Markdown format. It doesn't actually affect the instructions when they're rendered in ALH instructions.

Example:

8. Test  <- single space here means the instruction is not aligned with the rest.
9.  Test <- double space here, I have added for Steps 1-9 so it aligns. 
10. Test <- single space here for Steps 10 onwards to keep everything aligned.

This is why I have done this. This approach is inconsistently used across all the Biz Apps courses I have tested so far. Some do, some don't. I am trying to standardize where possible. I feel it makes it easier to read and scan through the instructions when they're aligned.

2023-04-21 07:53 UTC, ephiax20 commented on Instructions/Labs/M2 Manage manufacturing processes.md
> +    > Note: When you select **New**, you may need to change the dropdown in the selection menu to **Other**.
This use of greater-than > symbol here is not about describing UI. This is part of Markdown syntax to highlight the Note correctly, it changes the formatting and makes it easier to read the note.

This is about standardizing the markdown code. If I recall correctly, some notes have the > and some don't. I am trying to standardize whenever a Note appears in the instructions so they all look the same.

2023-06-02 17:46 UTC, closed without merging